name: SPALM GitHub Connections Example

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to connect to"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - test
          - prod

jobs:
  connect-and-run:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup PowerShell
        uses: actions/setup-powershell@v1
        with:
          powershell-version: "7.2"

      - name: Install required PowerShell modules
        shell: pwsh
        run: |
          Install-Module -Name PnP.PowerShell -Force -Scope CurrentUser

      - name: Set up connections from GitHub secrets
        shell: pwsh
        run: |
          # Load the module
          Import-Module ./src/SPALM/SPALM.psm1 -Force

          # Run the connection setup script
          . ./config/set-github-connections.ps1

          # Get target site URL based on environment
          $targetEnvironment = '${{ github.event.inputs.environment }}'

          # Connect using the connection created from secrets
          Connect-SPALMSite -ConnectionName $targetEnvironment

          # Show connected site
          $ctx = Get-PnPContext
          Write-Host "Connected to site: $($ctx.Url)"

          # Run your SPALM commands here
          # ...

          # Disconnect
          Disconnect-SPALMSite
        env:
          DEV_SITE_URL: ${{ secrets.DEV_SITE_URL }}
          TEST_SITE_URL: ${{ secrets.TEST_SITE_URL }}
          PROD_SITE_URL: ${{ secrets.PROD_SITE_URL }}
          SOURCE_SITE_URL: ${{ secrets.SOURCE_SITE_URL }}
          AZURE_APP_CLIENT_ID: ${{ secrets.AZURE_APP_CLIENT_ID }}
          AZURE_APP_CLIENT_SECRET: ${{ secrets.AZURE_APP_CLIENT_SECRET }}
          AZURE_APP_TENANT_ID: ${{ secrets.AZURE_APP_TENANT_ID }}
